import type { APIPolicyTemplate } from '../services/apiManagerService';

export const FALLBACK_API_POLICY_CATALOG: APIPolicyTemplate[] = [
  {
    id: 'rate-limiting-sla-based',
    name: 'Rate Limiting - SLA Based',
    description:
      'Specifies the maximum value for the number of messages processed per time period, and rejects any messages beyond the maximum.',
    category: 'Traffic Management',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: 'https://docs.mulesoft.com/anypoint-platform-for-apis/client-id-based-policies',
    providedCharacteristics: ['SLA Rate Limiting', 'Client ID required'],
    requiredCharacteristics: [],
    isSlaBased: true,
  },
  {
    id: 'rate-limiting',
    name: 'Rate Limiting',
    description:
      'Specifies the maximum value for the number of messages processed per time period, and rejects any messages beyond the maximum for all API calls.',
    category: 'Traffic Management',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['Rate limiting'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'spike-control',
    name: 'Spike Control',
    description:
      'Controls spikes in traffic by limiting the number of messages processed by an API using a sliding window algorithm.',
    category: 'Traffic Management',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['Spike control'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'http-caching',
    name: 'HTTP Caching',
    description: 'Provides caching service for HTTP requests.',
    category: 'Traffic Management',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['HTTP cache'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'tokenization',
    name: 'Tokenization',
    description: 'Protects sensitive values by tokenizing configured fields.',
    category: 'Security',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: 'https://docs.mulesoft.com/api-manager/2.x/policy-mule4-tokenization',
    providedCharacteristics: ['Tokenization'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'basic-authentication-simple',
    name: 'Basic Authentication - Simple',
    description: 'Enforces HTTP Basic authentication according to the configured policy details.',
    category: 'Security',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['Authentication'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'detokenization',
    name: 'Detokenization',
    description: 'Rehydrates tokenized values under controlled policy rules.',
    category: 'Security',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: 'https://docs.mulesoft.com/api-manager/2.x/policy-mule4-detokenization',
    providedCharacteristics: ['Detokenization'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'xml-threat-protection',
    name: 'XML Threat Protection',
    description: 'Protects against malicious XML in API requests.',
    category: 'Security',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['Threat protection'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'oauth2-provider',
    name: 'OAuth 2.0 Access Token Enforcement using Mule OAuth Provider',
    description:
      'Enforces use of an OAuth 2.0 access token issued through a Mule OAuth provider and may require API definition updates.',
    category: 'Security',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['OAuth 2.0'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'json-threat-protection',
    name: 'Json Threat Protection',
    description: 'Protects against malicious JSON in API requests.',
    category: 'Security',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['Threat protection'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'ip-blocklist',
    name: 'IP Blocklist',
    description: 'Denies service calls from a defined set of IP addresses.',
    category: 'Security',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['IP filtering'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'jwt-validation',
    name: 'JWT Validation',
    description: 'Requires a Json Web Token (JWT) to access the API.',
    category: 'Security',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['JWT'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'basic-authentication-ldap',
    name: 'Basic Authentication - LDAP',
    description: 'Enforces HTTP Basic authentication against the configured LDAP server.',
    category: 'Security',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['LDAP authentication'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'ip-allowlist',
    name: 'IP Allowlist',
    description: 'Limits service calls to a defined set of IP addresses.',
    category: 'Security',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['IP filtering'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'message-logging',
    name: 'Message Logging',
    description:
      'Logs custom messages between policies and flows, useful for troubleshooting and operational visibility.',
    category: 'Troubleshooting',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['Message logging'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'client-id-enforcement',
    name: 'Client ID Enforcement',
    description:
      'Requires a client ID and client secret for an application registered to use the API.',
    category: 'Compliance',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: 'https://docs.mulesoft.com/anypoint-platform-for-apis/client-id-based-policies',
    providedCharacteristics: ['Client ID required'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'cross-origin-resource-sharing',
    name: 'Cross-Origin Resource Sharing',
    description:
      'Allows JavaScript XHR calls executed in a web page to interact with resources from non-origin domains.',
    category: 'Compliance',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['CORS'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'header-injection',
    name: 'Header Injection',
    description: 'Allows header injection during message processing.',
    category: 'Transformation',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['Header transformation'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
  {
    id: 'header-removal',
    name: 'Header Removal',
    description: 'Allows header removal during message processing.',
    category: 'Transformation',
    groupId: null,
    assetId: null,
    assetVersion: null,
    docsUrl: null,
    providedCharacteristics: ['Header transformation'],
    requiredCharacteristics: [],
    isSlaBased: false,
  },
].map((template) => ({
  ...template,
  configurationFields: [],
}));
